// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFzyomDCSUoBSl7Lc0RybvN6FHYJRjK0M',
    appId: '1:16617969244:web:6bc421a8d3554f5f81b899',
    messagingSenderId: '16617969244',
    projectId: 'echo-attendance-app',
    authDomain: 'echo-attendance-app.firebaseapp.com',
    storageBucket: 'echo-attendance-app.firebasestorage.app',
    measurementId: 'G-XWWT822MHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwSpoPkY2Qei7lca4nG86aNrxCmb5YqLQ',
    appId: '1:16617969244:android:37d652f844d460d581b899',
    messagingSenderId: '16617969244',
    projectId: 'echo-attendance-app',
    storageBucket: 'echo-attendance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD_mb-rgKtBLXkOwL6YY1rfJmt5ulm2AM',
    appId: '1:16617969244:ios:8e07c76bb1c8a46181b899',
    messagingSenderId: '16617969244',
    projectId: 'echo-attendance-app',
    storageBucket: 'echo-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.attendify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD_mb-rgKtBLXkOwL6YY1rfJmt5ulm2AM',
    appId: '1:16617969244:ios:8e07c76bb1c8a46181b899',
    messagingSenderId: '16617969244',
    projectId: 'echo-attendance-app',
    storageBucket: 'echo-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.attendify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFzyomDCSUoBSl7Lc0RybvN6FHYJRjK0M',
    appId: '1:16617969244:web:a4847112a595b73181b899',
    messagingSenderId: '16617969244',
    projectId: 'echo-attendance-app',
    authDomain: 'echo-attendance-app.firebaseapp.com',
    storageBucket: 'echo-attendance-app.firebasestorage.app',
    measurementId: 'G-X492W0827P',
  );
}
